language: node_js
node_js:
- '10'

before_install:
- npm install -g @angular/cli
install: npm install


branches:
  only:
  - master

deploy:
  provider: heroku
  api_key:
    secure: "c64832ce-feb8-47ad-ae2a-cacdc1d7e8c0"
  app: app-test-ci