language: node_js
node_js:
- '10'

before_install:
- npm install -g @angular/cli
install: npm install


branches:
  only:
  - master

deploy:
  provider: heroku
  api_key:
    secure: "da6528d4-15b2-42d5-b658-e1ec54aa297f"
  app: app-test-ci